const PATH = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PRODUCT: '/product',
  PRODUCT_DETAIL: '/product/:name_id',
  PRODUCT_DETAIL_WITHOUT_ID: '/product',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:name_id',
  BLOG_DETAIL_WITHOUT_ID: '/blog',
  ACCOUNT: '/account',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_ORDER: '/account/orders',
  ACCOUNT_ORDER_DETAIL: '/account/orders/:order_id',
  ACCOUNT_ORDER_DETAIL_WITHOUT_ID: '/account/orders',
  ACCOUNT_VIEWED_PRODUCT: '/account/viewed-product',
  ACCOUNT_ADDRESS: '/account/address',
  ACCOUNT_CHANGE_PASSWORD: '/account/change-password',
  CART: '/cart',
  CART_LIST: '/cart/list',
  CART_CHECKOUT_INFO: '/cart/checkout-info',
  CART_CHECKOUT_PROCESS: '/cart/checkout-process',
  CART_CHECKOUT_SUCCESS: '/cart/checkout-success',
  SEARCH: '/search',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_RESET_PASSWORD_TOKEN: '/verify-reset-password-token',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',

  DASHBOARD: '/dashboard',
  DASHBOARD_USER: '/dashboard/user',
  DASHBOARD_CATEGORY: '/dashboard/category',
  DASHBOARD_CATEGORY_CREATE: '/dashboard/category/create',
  DASHBOARD_CATEGORY_UPDATE: '/dashboard/category/update/:category_id',
  DASHBOARD_CATEGORY_UPDATE_WITHOUT_ID: '/dashboard/category/update',
  DASHBOARD_BRAND: '/dashboard/brand',
  DASHBOARD_BRAND_CREATE: '/dashboard/brand/create',
  DASHBOARD_BRAND_UPDATE: '/dashboard/brand/update/:brand_id',
  DASHBOARD_BRAND_UPDATE_WITHOUT_ID: '/dashboard/brand/update',
  DASHBOARD_PRODUCT: '/dashboard/product',
  DASHBOARD_PRODUCT_CREATE: '/dashboard/product/create',
  DASHBOARD_PRODUCT_UPDATE: '/dashboard/product/update/:product_id',
  DASHBOARD_PRODUCT_UPDATE_WITHOUT_ID: '/dashboard/product/update',
  DASHBOARD_BLOG: '/dashboard/blog',
  DASHBOARD_BLOG_CREATE: '/dashboard/blog/create',
  DASHBOARD_BLOG_UPDATE: '/dashboard/blog/update/:blog_id',
  DASHBOARD_BLOG_UPDATE_WITHOUT_ID: '/dashboard/blog/update',
  DASHBOARD_ORDER: '/dashboard/order',
  DASHBOARD_ORDER_DETAIL: '/dashboard/order/:order_id',
  DASHBOARD_ORDER_DETAIL_WITHOUT_ID: '/dashboard/order',
  DASHBOARD_VOUCHER: '/dashboard/voucher',
  DASHBOARD_VOUCHER_CREATE: '/dashboard/voucher/create',
  DASHBOARD_VOUCHER_UPDATE: '/dashboard/voucher/update/:voucher_id',
  DASHBOARD_VOUCHER_UPDATE_WITHOUT_ID: '/dashboard/voucher/update',
  NOT_FOUND: '*'
} as const;

export default PATH;
