const PATH = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PRODUCT_DETAIL: '/product/:name_id',
  PRODUCT_DETAIL_WITHOUT_ID: '/product',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:name_id',
  BLOG_DETAIL_WITHOUT_ID: '/blog',
  ACCOUNT: '/account',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_ORDER: '/account/orders',
  ACCOUNT_ORDER_DETAIL: '/account/orders/:order_id',
  ACCOUNT_ORDER_DETAIL_WITHOUT_ID: '/account/orders',
  ACCOUNT_VIEWED_PRODUCT: '/account/viewed-product',
  ACCOUNT_ADDRESS: '/account/address',
  CART: '/cart',

  DASHBOARD: '/dashboard',
  DASHBOARD_USER: '/dashboard/user',
  DASHBOARD_CATEGORY: '/dashboard/category',
  DASHBOARD_CATEGORY_CREATE: '/dashboard/category/create',
  DASHBOARD_CATEGORY_UPDATE: '/dashboard/category/update/:category_id',
  DASHBOARD_CATEGORY_UPDATE_WITHOUT_ID: '/dashboard/category/update',
  DASHBOARD_BRAND: '/dashboard/brand',
  DASHBOARD_BRAND_CREATE: '/dashboard/brand/create',
  DASHBOARD_BRAND_UPDATE: '/dashboard/brand/update/:brand_id',
  DASHBOARD_BRAND_UPDATE_WITHOUT_ID: '/dashboard/brand/update',
  DASHBOARD_PRODUCT: '/dashboard/product',
  DASHBOARD_PRODUCT_CREATE: '/dashboard/product/create',
  DASHBOARD_PRODUCT_UPDATE: '/dashboard/product/update/:product_id',
  DASHBOARD_PRODUCT_UPDATE_WITHOUT_ID: '/dashboard/product/update',
  DASHBOARD_BLOG: '/dashboard/blog',
  DASHBOARD_BLOG_CREATE: '/dashboard/blog/create',
  DASHBOARD_BLOG_UPDATE: '/dashboard/blog/update/:blog_id',
  DASHBOARD_BLOG_UPDATE_WITHOUT_ID: '/dashboard/blog/update',
  NOT_FOUND: '*'
} as const;

export default PATH;
